# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otF5o4EcMEdK2fSJyz9oTmnQgbyjaeEB
"""

import glfw
import OpenGL.GL as gl
from imgui.integrations.glfw import GlfwRenderer
import imgui
import numpy as np
import util
import imageio
import util_gau
import tkinter as tk
from tkinter import filedialog
import os
import sys
import argparse
from renderer_ogl import OpenGLRenderer, GaussianRenderBase

# Add the directory containing main.py to the Python path
dir_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(dir_path)

# Change the current working directory to the script's directory
os.chdir(os.path.dirname(os.path.abspath(__file__)))

# Camera and renderer setup
g_camera = util.Camera(720, 1280)
BACKEND_OGL = 0
BACKEND_CUDA = 1
g_renderer_list = [None]  # ogl
g_renderer_idx = BACKEND_OGL
g_renderer: GaussianRenderBase = g_renderer_list[g_renderer_idx]
g_scale_modifier = 1.
g_auto_sort = False
g_show_control_win = True
g_show_help_win = True
g_show_camera_win = False
g_render_mode_tables = ["Gaussian Ball", "Flat Ball", "Billboard", "Depth", "SH:0", "SH:0~1", "SH:0~2", "SH:0~3 (default)"]
g_render_mode = 7

# Ray picking: translate screen coordinates to 3D coordinates
def get_ray_from_screen_coordinates(x, y, width, height, camera):
    # Normalize screen coordinates
    normalized_x = (2.0 * x) / width - 1.0
    normalized_y = 1.0 - (2.0 * y) / height  # OpenGL coordinates have y inverted
    # Create a ray using camera projection matrix
    ray_clip = np.array([normalized_x, normalized_y, -1.0, 1.0])
    ray_eye = np.linalg.inv(camera.get_proj_matrix()) @ ray_clip
    ray_eye = np.array([ray_eye[0], ray_eye[1], -1.0])  # ignoring w for simplicity
    ray_world = np.linalg.inv(camera.get_view_matrix()) @ np.append(ray_eye, 0.0)
    return ray_world[:3]  # Return the ray in world coordinates

# Store the selected point's position
selected_point_before = None
selected_point_after = None

# Mouse callback for picking points
def mouse_button_callback(window, button, action, mod):
    global selected_point_before
    if imgui.get_io().want_capture_mouse:
        return
    if action == glfw.PRESS and button == glfw.MOUSE_BUTTON_LEFT:
        # Get mouse position and convert to world coordinates
        width, height = glfw.get_framebuffer_size(window)
        xpos, ypos = glfw.get_cursor_pos(window)
        ray = get_ray_from_screen_coordinates(xpos, ypos, width, height, g_camera)
        print(f"Ray at clicked position: {ray}")
        # For simplicity, use a point from the ray for now
        selected_point_before = ray  # Store the point before splatting
        print(f"Selected point before splatting: {selected_point_before}")

# Function to simulate Gaussian splatting (dummy function)
def apply_gaussian_splatting(point):
    # Simulating the effect of Gaussian splatting by applying a small translation
    return point + np.array([0.1, 0.1, 0.1])  # Just a small translation for illustration

# Update to track point after Gaussian splatting
def update_selected_point_after():
    global selected_point_before, selected_point_after
    if selected_point_before is not None:
        selected_point_after = apply_gaussian_splatting(selected_point_before)
        print(f"Selected point after splatting: {selected_point_after}")

# Initialize and setup OpenGL, GUI, and event loop
def impl_glfw_init():
    window_name = "NeUVF editor"

    if not glfw.init():
        print("Could not initialize OpenGL context")
        exit(1)

    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 4)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)

    global window
    window = glfw.create_window(g_camera.w, g_camera.h, window_name, None, None)
    glfw.make_context_current(window)
    glfw.swap_interval(0)

    if not window:
        glfw.terminate()
        print("Could not initialize Window")
        exit(1)

    return window

# Main application loop
def main():
    global g_camera, g_renderer, g_renderer_list, g_renderer_idx, g_scale_modifier, g_auto_sort, \
        g_show_control_win, g_show_help_win, g_show_camera_win, g_render_mode, g_render_mode_tables

    imgui.create_context()
    window = impl_glfw_init()
    impl = GlfwRenderer(window)
    root = tk.Tk()
    root.withdraw()

    glfw.set_mouse_button_callback(window, mouse_button_callback)

    g_renderer_list[BACKEND_OGL] = OpenGLRenderer(g_camera.w, g_camera.h)

    # Gaussian data
    gaussians = util_gau.naive_gaussian()
    update_activated_renderer_state(gaussians)

    # Main loop
    while not glfw.window_should_close(window):
        glfw.poll_events()
        impl.process_inputs()
        imgui.new_frame()

        gl.glClearColor(0, 0, 0, 1.0)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)

        update_camera_pose_lazy()
        update_camera_intrin_lazy()

        g_renderer.draw()
        update_selected_point_after()  # Update selected point after splatting

        # GUI controls
        if imgui.begin_main_menu_bar():
            if imgui.begin_menu("Window", True):
                clicked, g_show_control_win = imgui.menu_item("Show Control", None, g_show_control_win)
                clicked, g_show_help_win = imgui.menu_item("Show Help", None, g_show_help_win)
                imgui.end_menu()
            imgui.end_main_menu_bar()

        imgui.render()
        impl.render(imgui.get_draw_data())
        glfw.swap_buffers(window)

    impl.shutdown()
    glfw.terminate()

if __name__ == "__main__":
    global args
    parser = argparse.ArgumentParser(description="NeUVF editor with optional HiDPI support.")
    parser.add_argument("--hidpi", action="store_true", help="Enable HiDPI scaling for the interface.")
    args = parser.parse_args()

    main()